import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const roboto = Roboto({ weight: ['400','700'], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar></Navbar>
        <main className="py-20 max-w-6xl mx-auto">{children}</main>
        </body>
    </html>
  );
}


//things on layout is applied to all pages
//if we want to overide something, create a different layout for that page